src/NHibernate.Example.Web/Models/Item.cs
namespace NHibernate.Example.Web.Models
{
	public class Item
	{
		public virtual int Id { get; set; }
		public virtual decimal Price { get; set; }
		public virtual string Description { get; set; }
	}
}

src/NHibernate.Example.Web/Models/ItemMap.cs
using NHibernate.Mapping.ByCode;
using NHibernate.Mapping.ByCode.Conformist;

namespace NHibernate.Example.Web.Models
{
	public class ItemMap : ClassMapping<Item>
	{
		public ItemMap()
		{
			Lazy(false);
			Id(x => x.Id, map => map.Generator(Generators.Native));
			Property(x => x.Price);
			Property(x => x.Description);
		}
	}
}

src/NHibernate.Example.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NHibernate.Example.Web.Pages
{
	public class ErrorModel : PageModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

src/NHibernate.Example.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NHibernate.Example.Web.Pages
{
	public class IndexModel : PageModel
	{
		public void OnGet()
		{
		}
	}
}

src/NHibernate.Example.Web/Pages/InsertItem.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NHibernate.Example.Web.Models;

namespace NHibernate.Example.Web.Pages
{
	public class InsertItemModel : PageModel
	{
		[BindProperty]
		public InsertItemEvent NewItem { get; set; }

		private readonly ISession _session;

		public InsertItemModel(ISession session)
		{
			_session = session;
		}

		public void OnGet()
		{
		}

		public IActionResult OnPost()
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			using (var tx = _session.BeginTransaction())
			{
				var item = new Item
				{
					Price = NewItem.Price,
					Description = NewItem.Description,
				};
				_session.Save(item);

				tx.Commit();
			}

			return RedirectToPage("/ViewData");
		}

		public IActionResult OnPostCancel()
		{
			return RedirectToPage("/ViewData");
		}

		public class InsertItemEvent
		{
			[Required, Range(0.0, double.MaxValue)]
			public decimal Price { get; set; }

			public string Description { get; set; }
		}
	}
}

src/NHibernate.Example.Web/Pages/Schema.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NHibernate.Example.Web.Infrastructure;
using NHibernate.Example.Web.Models;
using NHibernate.Tool.hbm2ddl;

namespace NHibernate.Example.Web.Pages
{
	public class SchemaModel : PageModel
	{
		[TempData]
		public string Status { get; set; }

		private readonly AppSessionFactory _applicationSession;
		private readonly ISession _session;

		public SchemaModel(ISession session, AppSessionFactory applicationSession)
		{
			_applicationSession = applicationSession;
			_session = session ?? throw new ArgumentNullException(nameof(session));
		}

		public void OnGet()
		{
		}

		public IActionResult OnPostCreateSchema()
		{
			var export = new SchemaExport(_applicationSession.Configuration);
			export.Create(false, true);

			using (var tx = _session.BeginTransaction())
			{
				var item1 = new Item
				{
					Description = "First item",
					Price = 100m
				};
				_session.Save(item1);

				var item2 = new Item
				{
					Description = "Second item",
					Price = 150m
				};
				_session.Save(item2);

				tx.Commit();
			}

			Status = "Schema created";
			return RedirectToPage();
		}

		public IActionResult OnPostDropSchema()
		{
			SchemaExport export = new SchemaExport(_applicationSession.Configuration);
			export.Drop(false, true);

			Status = "Schema dropped";
			return RedirectToPage();
		}
	}
}

src/NHibernate.Example.Web/Pages/ViewData.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NHibernate.Example.Web.Models;

namespace NHibernate.Example.Web.Pages
{
	public class ViewDataModel : PageModel
	{
		public IList<Item> Items { get; set; }
		public int? Editing { get; set; }

		private readonly ISession _session;

		public ViewDataModel(ISession session)
		{
			_session = session;
		}

		public void OnGet(int? editing)
		{
			Editing = editing;

			using (var tx = _session.BeginTransaction())
			{
				Items = _session.QueryOver<Item>().List();
			}
		}

		public IActionResult OnPostEdit(int id)
		{
			return RedirectToPage(new {editing = id});
		}

		public IActionResult OnPostDelete(int id)
		{
			using (var tx = _session.BeginTransaction())
			{
				var item = _session.Get<Item>(id);
				if (item != null)
				{
					_session.Delete(item);
				}

				tx.Commit();
			}

			return RedirectToPage();
		}

		public IActionResult OnPostUpdate(int id, UpdateItemEvent updateItem)
		{
			if (!ModelState.IsValid)
			{
				return Page();
			}

			using (var tx = _session.BeginTransaction())
			{
				var item = _session.Get<Item>(id);
				if (item != null)
				{
					item.Price = updateItem.Price;
					item.Description = updateItem.Description;
					_session.Update(item);
				}

				tx.Commit();
			}

			return RedirectToPage();
		}

		public IActionResult OnPostCancelUpdate()
		{
			return RedirectToPage();
		}

		public class UpdateItemEvent
		{
			[Required, Range(0.0, double.MaxValue)]
			public decimal Price { get; set; }
			public string Description { get; set; }
		}
	}
}

src/NHibernate.Example.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "NHibernate Demo";
}

<h1>NHibernate Demo</h1>
<a href="~/Schema">Schema Operations</a>
<a href="~/ViewData">View Data</a>

src/NHibernate.Example.Web/Pages/InsertItem.cshtml
@page
@model InsertItemModel
@{
    ViewData["Title"] = "Insert New Item";
}
<form method="POST">
    <table>
        <tr>
            <td>Price:</td><td><input type="number" min="0" step="any" asp-for="NewItem.Price"/></td>
        </tr>
        <tr>
            <td>Description:</td><td><input asp-for="NewItem.Description"/></td>
        </tr>
        <tr>
            <td></td>
            <td><button type="submit">OK</button><button type="submit" asp-page-handler="Cancel">Cancel</button></td>
        </tr>
    </table>
</form>

src/NHibernate.Example.Web/Pages/Schema.cshtml
@page
@model SchemaModel
@{
    ViewData["Title"] = "Schema Operations";
}

<a href="~/">Back to the main page</a>

<form method="POST">
    <div>
        <button type="submit" asp-page-handler="CreateSchema">Create Schema</button>
        <button type="submit" asp-page-handler="DropSchema">Drop Schema</button>
    </div>
</form>

<p>@Model.Status</p>

src/NHibernate.Example.Web/Pages/ViewData.cshtml
@page
@model ViewDataModel
@{
    ViewData["Title"] = "View Items";
}

<form method="POST">
    <table class="itemlist">
        <caption>Item List</caption>
        <thead>
        <tr><th> </th><th>Id</th><th>Price</th><th>Description</th></tr>
        </thead>
        @foreach (var item in Model.Items)
        {
            <tr>
                @if (Model.Editing == item.Id)
                {
                    <td>
                        <button class="link" type="submit" asp-page-handler="Update" asp-route-id="@item.Id">Update</button>
                        <button class="link" type="submit" asp-page-handler="CancelUpdate">Cancel</button>
                    </td>
                    <td>@item.Id</td>
                    <td><input type="number" min="0" step="any" name="Price" value="@item.Price" /></td>
                    <td><input type="text" name="Description" value="@item.Description" /></td>
                }
                else
                {
                    <td>
                        <button class="link" type="submit" asp-page-handler="Edit" asp-route-id="@item.Id">Edit</button>
                        <button class="link" type="submit" asp-page-handler="Delete" asp-route-id="@item.Id">Delete</button>
                    </td>
                    <td>@item.Id</td>
                    <td>@item.Price</td>
                    <td>@item.Description</td>
                }
            </tr>
        }
    </table>
</form>
<a href="~/InsertItem">Add New Item</a>

src/NHibernate.Example.Web/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <style>
        button.link {
            background: none !important;
            color: rgb(0, 0, 238);
            border: none;
            padding: 0 !important;
            font: inherit;
            text-decoration-color: rgb(0, 0, 238);
            text-decoration-line: underline;
            text-decoration-style: solid;
            cursor: pointer;
        }
        table.itemlist {
            border-spacing: 0;
            border-collapse: collapse;
            border: 1px solid black;
        }
        .itemlist td{
            border: 1px solid black;
        }
        .itemlist th {
            border: 1px solid black;
        }
    </style>
</head>
<body>
    @RenderBody()

<p>
    @Microsoft.Extensions.PlatformAbstractions.PlatformServices.Default.Application.RuntimeFramework
</p>

@RenderSection("Scripts", required: false)
</body>
</html>